apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: financial-data-pipeline-template
  namespace: financial-mlops-pytorch
spec:
  entrypoint: data-ingestion-and-feature-engineering
  serviceAccountName: argo-workflow-sa
  
  # Global resource defaults for all containers
  podGC:
    strategy: OnPodSuccess
  
  # Resource requirements for Argo system containers
  podSpecPatch: |
    initContainers:
    - name: init
      resources:
        requests:
          cpu: 100m
          memory: 128Mi
        limits:
          cpu: 500m
          memory: 256Mi
    containers:
    - name: wait
      resources:
        requests:
          cpu: 100m
          memory: 128Mi
        limits:
          cpu: 500m
          memory: 256Mi
    - name: main
      resources:
        requests:
          cpu: 1
          memory: 2Gi
        limits:
          cpu: 2
          memory: 4Gi
  
  volumes:
  - name: shared-data-pvc
    persistentVolumeClaim:
      claimName: shared-data-pvc  # Reference the pre-created PVC
  - name: shared-artifacts-pvc
    persistentVolumeClaim:
      claimName: shared-artifacts-pvc
  - metadata:
      name: shared-artifacts-pvc
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: nfs-shared # Use default storage class or specify your NFS storage class
      resources:
        requests:
          storage: 1Gi

  templates:
  - name: data-ingestion-and-feature-engineering
    dag:
      tasks:
      - name: ingest-data
        template: ingest-stock-data
      - name: engineer-features
        dependencies: [ingest-data]
        template: process-and-engineer-features

  - name: ingest-stock-data
    container:
      image: jtayl22/financial-predictor:latest
      command: ["python", "src/data_ingestion.py"]
      envFrom:
        - secretRef:
            name: ml-platform
      env:
      - name: LOGLEVEL
        value: "INFO"
      - name: RAW_DATA_DIR
        value: "/mnt/shared-data/raw"
      - name: INGESTION_START_DATE
        value: "2018-01-01"
      - name: INGESTION_END_DATE
        value: "2023-12-31"
      - name: TICKERS
        value: "AAPL,MSFT"
      volumeMounts:
        - name: shared-data-pvc
          mountPath: /mnt/shared-data
        - name: shared-artifacts-pvc
          mountPath: /mnt/shared-artifacts
      resources:
        requests:
          memory: "2Gi"  # Fix 2: Reduced memory requests
          cpu: "1"
        limits:
          memory: "4Gi"  # Fix 3: More reasonable limits
          cpu: "2"
      # Fix 4: Add security context if needed
      securityContext:
        runAsNonRoot: false
        runAsUser: 0

  - name: process-and-engineer-features
    container:
      image: jtayl22/financial-predictor:latest
      command: ["python", "src/feature_engineering_pytorch.py"]
      envFrom:
        - secretRef:
            name: ml-platform
      env:
      - name: MLFLOW_TRACKING_URI
        value: "http://mlflow.mlflow.svc.cluster.local:5000"
      - name: RAW_DATA_DIR
        value: "/mnt/shared-data/raw"
      - name: PROCESSED_DATA_DIR
        value: "/mnt/shared-data/processed"
      - name: SCALER_DIR
        value: "/mnt/shared-artifacts/scalers"
      - name: SEQUENCE_LENGTH
        value: "10"
      volumeMounts:
        - name: shared-data-pvc
          mountPath: /mnt/shared-data
        - name: shared-artifacts-pvc
          mountPath: /mnt/shared-artifacts
      resources:
        requests:
          memory: "2Gi"
          cpu: "1"
        limits:
          memory: "4Gi"
          cpu: "2"
      securityContext:
        runAsNonRoot: false
        runAsUser: 0
  
  # imagePullSecrets:
  # - name: ghcr
