---
apiVersion: mlops.seldon.io/v1alpha1
kind: Model
metadata:
  name: baseline-predictor
  namespace: financial-ml
spec:
  storageUri: s3://mlflow-artifacts/28/models/m-4848a05187b24af79a8d93333de1d41d/artifacts/
  requirements:
  - mlflow
  - torch
  - numpy
  - scikit-learn
  secretName: ml-platform
  server: mlserver

---
apiVersion: mlops.seldon.io/v1alpha1
kind: Model
metadata:
  name: enhanced-predictor
  namespace: financial-ml
spec:
  storageUri: s3://mlflow-artifacts/29/models/m-d64ffcb77a684fbfa8597e439c920a07/artifacts/
  requirements:
  - mlflow
  - torch
  - numpy
  - scikit-learn
  secretName: ml-platform
  server: mlserver

---
apiVersion: mlops.seldon.io/v1alpha1
kind: Experiment
metadata:
  name: financial-ab-test-experiment
  namespace: financial-ml
spec:
  default: baseline-predictor
  candidates:
  - name: baseline-predictor
    weight: 70
  - name: enhanced-predictor
    weight: 30

