---
apiVersion: mlops.seldon.io/v1alpha1
kind: Model
metadata:
  name: baseline-predictor
  namespace: financial-inference
  labels:
    app.kubernetes.io/name: financial-mlops-pytorch
    app.kubernetes.io/part-of: ml-platform
    app.kubernetes.io/managed-by: kustomize
spec:
  storageUri: s3://mlflow-artifacts/29/models/m-63118756949141cba59ab87e90e8a96a/artifacts/
  requirements:
  - mlflow
  - torch
  - numpy
  - sklearn
  server: mlserver

---
apiVersion: mlops.seldon.io/v1alpha1
kind: Model
metadata:
  name: enhanced-predictor
  namespace: financial-inference
  labels:
    app.kubernetes.io/name: financial-mlops-pytorch
    app.kubernetes.io/part-of: ml-platform
    app.kubernetes.io/managed-by: kustomize
spec:
  storageUri: s3://mlflow-artifacts/29/models/m-c33f0084469e4473a1ba9d428657299f/artifacts/
  requirements:
  - mlflow
  - torch
  - numpy
  - sklearn
  server: mlserver

---
apiVersion: mlops.seldon.io/v1alpha1
kind: Experiment
metadata:
  name: financial-ab-test-experiment
  namespace: financial-inference
  labels:
    app.kubernetes.io/name: financial-mlops-pytorch
    app.kubernetes.io/part-of: ml-platform
    app.kubernetes.io/managed-by: kustomize
spec:
  default: baseline-predictor
  candidates:
  - name: baseline-predictor
    weight: 70
  - name: enhanced-predictor
    weight: 30

