---
apiVersion: mlops.seldon.io/v1alpha1
kind: Model
metadata:
  name: baseline-predictor
  namespace: financial-ml
spec:
  storageUri: s3://mlflow-artifacts/28/models/m-d6d788df1b5849b3a3df1d04434c17b9/artifacts/
  requirements:
  - mlflow
  - torch
  - numpy
  - scikit-learn
  secretName: ml-platform
  server: mlserver

---
apiVersion: mlops.seldon.io/v1alpha1
kind: Model
metadata:
  name: enhanced-predictor
  namespace: financial-ml
spec:
  storageUri: s3://mlflow-artifacts/29/models/m-232922a2285b471d8fc0740fd9ff1551/artifacts/
  requirements:
  - mlflow
  - torch
  - numpy
  - scikit-learn
  secretName: ml-platform
  server: mlserver

---
apiVersion: mlops.seldon.io/v1alpha1
kind: Experiment
metadata:
  name: financial-ab-test-experiment
  namespace: financial-ml
spec:
  default: baseline-predictor
  candidates:
  - name: baseline-predictor
    weight: 70
  - name: enhanced-predictor
    weight: 30

