---
apiVersion: mlops.seldon.io/v1alpha1
kind: Model
metadata:
  name: baseline-predictor
  namespace: seldon-system
  labels:
    app.kubernetes.io/name: seldon-system
    app.kubernetes.io/part-of: ml-platform
    app.kubernetes.io/managed-by: kustomize
spec:
  storageUri: models:/FinancialDirectionPredictor_Baseline/Production
  requirements:
  - mlflow
  - torch
  - numpy
  - sklearn
  server: mlserver

---
apiVersion: mlops.seldon.io/v1alpha1
kind: Model
metadata:
  name: advanced-predictor
  namespace: seldon-system
  labels:
    app.kubernetes.io/name: seldon-system
    app.kubernetes.io/part-of: ml-platform
    app.kubernetes.io/managed-by: kustomize
spec:
  storageUri: models:/FinancialDirectionPredictor_Advanced/Production
  requirements:
  - mlflow
  - torch
  - numpy
  - sklearn
  server: mlserver

---
apiVersion: mlops.seldon.io/v1alpha1
kind: Experiment
metadata:
  name: financial-ab-test-experiment
  namespace: seldon-system
  labels:
    app.kubernetes.io/name: seldon-system
    app.kubernetes.io/part-of: ml-platform
    app.kubernetes.io/managed-by: kustomize
spec:
  default: baseline-predictor
  candidates:
  - name: baseline-predictor
    weight: 70
  - name: advanced-predictor
    weight: 30

