apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - sensor.yaml
  - event-source.yaml
  - applications.yaml
  - financial-predictor-ab-test.yaml
  - training-pipeline.yaml
  - financial-data-pipeline.yaml
  - rbac.yaml
  - shared-artifacts-pvc.yaml
  - shared-data-pvc.yaml
  - financial-data-pvc.yaml  # New dedicated financial data PVCs
  - financial-predictor-vs.yaml
  - seldon-runtime.yaml
  - server-config-scoped.yaml
  - network-policy.yaml
  - mlserver.yaml
  - nginx-ingress.yaml

labels:
- includeSelectors: false
  pairs:
    app.kubernetes.io/name: seldon-system
    app.kubernetes.io/part-of: ml-platform
    app.kubernetes.io/managed-by: kustomize
