apiVersion: mlops.seldon.io/v1alpha1
kind: Server
metadata:
  name: mlserver
  namespace: financial-inference
  labels:
    app.kubernetes.io/name: financial-mlops-pytorch
    app.kubernetes.io/part-of: ml-platform
    app.kubernetes.io/managed-by: kustomize
spec:
  serverConfig: mlserver
  capabilities: ["mlflow", "torch", "scikit-learn", "numpy"]
  replicas: 1