apiVersion: v1
kind: ServiceAccount
metadata:
  name: financial-mlops-sa
  namespace: financial-mlops-pytorch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: financial-mlops-role
  namespace: financial-mlops-pytorch
rules:
  - apiGroups: [""]
    resources: ["pods", "pods/log", "services", "configmaps", "secrets"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["batch", "extensions"]
    resources: ["jobs"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["argoproj.io"]
    resources: ["workflows", "workflowtaskresults"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: financial-mlops-rolebinding
  namespace: financial-mlops-pytorch
subjects:
  - kind: ServiceAccount
    name: financial-mlops-sa
    namespace: financial-mlops-pytorch
roleRef:
  kind: Role
  name: financial-mlops-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: argo-workflow-sa
  namespace: financial-mlops-pytorch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: argo-workflow-rolebinding
  namespace: financial-mlops-pytorch
subjects:
  - kind: ServiceAccount
    name: argo-workflow-sa
    namespace: financial-mlops-pytorch
roleRef:
  kind: Role
  name: financial-mlops-role
  apiGroup: rbac.authorization.k8s.io
