apiVersion: v1
kind: ServiceAccount
metadata:
  name: financial-mlops-sa
  namespace: seldon-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: financial-mlops-role
  namespace: seldon-system
rules:
  - apiGroups: [""]
    resources: ["pods", "pods/log", "services", "configmaps", "secrets"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["batch", "extensions"]
    resources: ["jobs"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["argoproj.io"]
    resources: ["workflows", "workflowtaskresults"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: financial-mlops-rolebinding
  namespace: seldon-system
subjects:
  - kind: ServiceAccount
    name: financial-mlops-sa
    namespace: seldon-system
roleRef:
  kind: Role
  name: financial-mlops-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: argo-workflow-sa
  namespace: seldon-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: argo-workflow-rolebinding
  namespace: seldon-system
subjects:
  - kind: ServiceAccount
    name: argo-workflow-sa
    namespace: seldon-system
roleRef:
  kind: Role
  name: financial-mlops-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: seldon-system
  name: model-deployer
rules:
- apiGroups: ["mlops.seldon.io"]
  resources: ["models", "experiments"]
  verbs: ["get", "list", "create", "update", "patch", "delete"]
- apiGroups: [""]
  resources: ["configmaps", "secrets", "services", "pods"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: mlserver-rolebinding
  namespace: seldon-system
subjects:
- kind: ServiceAccount
  name: default
  namespace: seldon-system
roleRef:
  kind: Role
  name: model-deployer
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: seldon-system-quota
  namespace: seldon-system
spec:
  hard:
    requests.cpu: "10"
    requests.memory: 50Gi
    limits.cpu: "20"
    limits.memory: 100Gi
    count/models.mlops.seldon.io: "50"
    count/pods: "50"
    count/workflows.argoproj.io: "50"
