---
apiVersion: mlops.seldon.io/v1alpha1
kind: SeldonRuntime
metadata:
  name: financial-inference-runtime
  namespace: financial-inference
  labels:
    app.kubernetes.io/name: financial-mlops-pytorch
    app.kubernetes.io/part-of: ml-platform
    app.kubernetes.io/managed-by: kustomize
spec:
  config:
    agentConfig:
      rclone: {}
    kafkaConfig: {}
    serviceConfig: {}
    tracingConfig: {}
  overrides:
  - name: hodometer
    replicas: 1
  - name: seldon-scheduler
    replicas: 0
  - name: seldon-envoy
    replicas: 1
  - name: seldon-dataflow-engine
    replicas: 0
  - name: seldon-modelgateway
    replicas: 1
  - name: seldon-pipelinegateway
    replicas: 0
  - name: mlserver
    replicas: 1
    env:
    - name: SELDON_SCHEDULER_HOST
      value: seldon-system-scheduler
    - name: SELDON_SCHEDULER_PORT
      value: "9004"
  seldonConfig: default