---
apiVersion: mlops.seldon.io/v1alpha1
kind: SeldonRuntime
metadata:
  name: financial-mlops-runtime
  namespace: financial-mlops-pytorch
  labels:
    app.kubernetes.io/name: financial-mlops-pytorch
    app.kubernetes.io/part-of: ml-platform
    app.kubernetes.io/managed-by: kustomize
spec:
  config:
    agentConfig:
      rclone:
        config_secrets:
        - seldon-rclone-gs-public
        - ml-platform
    kafkaConfig: {}
    serviceConfig: {}
    tracingConfig: {}
  overrides:
  - name: hodometer
    replicas: 1
  - name: seldon-scheduler
    replicas: 1
    podSpec:
      containers:
      - name: scheduler
        image: 192.168.1.210/library/seldon-scheduler:verbose-logging-working
        imagePullPolicy: Always
  - name: seldon-envoy
    replicas: 1
  - name: seldon-dataflow-engine
    replicas: 0
  - name: seldon-modelgateway
    replicas: 1
  - name: seldon-pipelinegateway
    replicas: 0
  - name: mlserver
    replicas: 1
  seldonConfig: default