---
apiVersion: mlops.seldon.io/v1alpha1
kind: ServerConfig
metadata:
  name: mlserver-config
  namespace: seldon-system
  labels:
    app.kubernetes.io/name: seldon-system
    app.kubernetes.io/part-of: ml-platform
    app.kubernetes.io/managed-by: kustomize
spec:
  podSpec:
    containers:
    - name: agent
      image: seldonio/seldon-agent:2.9.1
      resources:
        requests:
          cpu: 200m
          memory: 1Gi
        limits:
          cpu: 500m
          memory: 2Gi
    - name: mlserver
      image: seldonio/mlserver:1.6.0
      env:
      - name: MLSERVER_PARALLEL_WORKERS
        value: "4"
      - name: MLSERVER_MAX_GRPC_WORKERS
        value: "10"
      resources:
        requests:
          cpu: 500m
          memory: 2Gi
        limits:
          cpu: 1000m
          memory: 4Gi
  volumeClaimTemplates:
  - name: mlserver-models
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 1Gi