apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: financial-training-pipeline-template
  namespace: financial-mlops-pytorch
spec:
  entrypoint: train-model
  serviceAccountName: argo-workflow-sa
  volumes:
  - name: shared-data-pvc
    persistentVolumeClaim:
      claimName: shared-data-pvc
  - name: shared-artifacts-pvc
    persistentVolumeClaim:
      claimName: shared-artifacts-pvc
  - metadata:
      name: shared-artifacts-pvc
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: nfs-shared
      resources:
        requests:
          storage: 1Gi

  templates:
  - name: train-model
    container:
      image: jtayl22/financial-predictor:latest
      command: ["python", "src/train_pytorch_model.py"]
      env:
      - name: MLFLOW_TRACKING_URI
        value: "http://mlflow.mlflow.svc.cluster.local:5000"
      - name: PROCESSED_DATA_INPUT_DIR
        value: "/mnt/shared-data/processed"
      - name: SCALER_INPUT_DIR
        value: "/mnt/shared-artifacts/scalers"
      - name: MODEL_SAVE_DIR
        value: "/mnt/shared-models"
      - name: EPOCHS
        value: "20"
      - name: BATCH_SIZE
        value: "64"
      - name: LEARNING_RATE
        value: "0.001"
      - name: SEQUENCE_LENGTH
        value: "10"
      envFrom:
        - secretRef:
            name: ml-platform
      volumeMounts:
        - name: shared-data-pvc
          mountPath: /mnt/shared-data
        - name: shared-artifacts-pvc
          mountPath: /mnt/shared-artifacts
      resources:
        requests:
          memory: "2Gi"
          cpu: "1"
        limits:
          memory: "4Gi"
          cpu: "2"
    imagePullSecrets:
      - name: ghcr