apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: financial-training-pipeline-template
  namespace: seldon-system
spec:
  entrypoint: train-model
  serviceAccountName: argo-workflow-sa
  
  podSpecPatch: |
    initContainers:
    - name: init
      resources:
        requests:
          cpu: 100m
          memory: 128Mi
        limits:
          cpu: 500m
          memory: 256Mi
    containers:
    - name: wait
      resources:
        requests:
          cpu: 100m
          memory: 128Mi
        limits:
          cpu: 500m
          memory: 256Mi

  volumes:
  - name: shared-data-pvc
    persistentVolumeClaim:
      claimName: shared-data-pvc
  - name: shared-artifacts-pvc
    persistentVolumeClaim:
      claimName: shared-artifacts-pvc

  templates:
  - name: train-model
    inputs:
      parameters:
      - name: model-variant
        value: baseline  # Default value, can be overridden by the sensor
    container:
      image: jtayl22/financial-predictor:latest
      command: ["python", "src/train_pytorch_model.py"]
      env:
      - name: MODEL_VARIANT
        value: "{{inputs.parameters.model-variant}}"
      - name: MLFLOW_TRACKING_URI
        value: "http://mlflow.mlflow.svc.cluster.local:5000"
      - name: PROCESSED_DATA_DIR
        value: "/mnt/shared-data/processed"
      - name: SCALER_DIR
        value: "/mnt/shared-artifacts/scalers"
      - name: MODEL_SAVE_DIR
        value: "/mnt/shared-models"
      - name: EPOCHS
        value: "20"
      - name: BATCH_SIZE
        value: "64"
      - name: LEARNING_RATE
        value: "0.001"
      - name: SEQUENCE_LENGTH
        value: "10"
      - name: LOGLEVEL
        value: "INFO"
      envFrom:
        - secretRef:
            name: ml-platform
      volumeMounts:
        - name: shared-data-pvc
          mountPath: /mnt/shared-data
        - name: shared-artifacts-pvc
          mountPath: /mnt/shared-artifacts
      resources:
        requests:
          memory: "4Gi"
          cpu: "2"
        limits:
          memory: "8Gi"
          cpu: "4"
  
  # imagePullSecrets:
  # - name: ghcr